name: Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint the codebase
        run: bun x eslint src tests

      - name: Pull Vercel Environment Information
        run: bun x vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: bun x vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Calculate build size and display
        run: |
          SIZE_CURRENT=$(du -sk dist | cut -f1)
          SIZE_MAIN=$(bun .github/check.ts)
          SIZE_DIFF=$(($SIZE_CURRENT-$SIZE_MAIN))
          echo "# Build Summary" >>  $GITHUB_STEP_SUMMARY
          echo "Total build size: $SIZE_CURRENT KB ($SIZE_DIFF KB diff)" >>  $GITHUB_STEP_SUMMARY
          echo "## Individual file sizes" >> $GITHUB_STEP_SUMMARY
          echo "|Path|Size|" >> $GITHUB_STEP_SUMMARY
          echo "|-|-|" >> $GITHUB_STEP_SUMMARY
          cd dist && find . -type f -printf "| %-40p | %-5k KB |\n" >> $GITHUB_STEP_SUMMARY
          echo "::notice title=Build Size::Total build size: $SIZE_CURRENT KB ($SIZE_DIFF KB diff)"

        id: build_size

      - name: Deploy Project Artifacts to Vercel
        id: deploy-preview
        run: |
          bun x vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > vercel-domain.txt
          echo "VERCEL_DEPLOYMENT_URL=$(cat vercel-domain.txt)" >> $GITHUB_OUTPUT
          echo "# Preview URL" >> $GITHUB_STEP_SUMMARY
          echo "$(cat vercel-domain.txt)" >> $GITHUB_STEP_SUMMARY
          echo "::notice title=Preview URL::$(cat vercel-domain.txt)"

    outputs:
      VERCEL_DEPLOYMENT_URL: ${{ steps.deploy-preview.outputs.VERCEL_DEPLOYMENT_URL }}

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup Playwright
        run: bun x playwright install --with-deps chromium

      - name: Run Playwright tests
        run: bun run test:playwright
        env:
          PLAYWRIGHT_BASE_URL: ${{ needs.build.outputs.VERCEL_DEPLOYMENT_URL }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest

    needs: test

    if: github.ref == 'refs/heads/main'

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Pull Vercel Environment Information
        run: bun x vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}


      - name: Build Project Artifacts
        run: bun x vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy-prod
        run: |
          bun x vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod > vercel-domain.txt
          echo "VERCEL_DEPLOYMENT_URL=$(cat vercel-domain.txt)" >> $GITHUB_OUTPUT
